USE `asterisk`;
DELETE FROM `asterisk`.`endpointman_model_list` WHERE `id`='2411';
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('271', '2', 'HT701', '1', 'general.json', '27', '0', '0');
INSERT INTO `asterisk`.`endpointman_product_list` (`id`, `brand`, `long_name`, `short_name`, `cfg_dir`, `config_files`) VALUES ('27', '2', 'HandyTone ATA [HT701,HT702]', 'HandyTone ATA', 'ht70x', 'cfg$mac');
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24100' WHERE `id`='244';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24200' WHERE `id`='245';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24300' WHERE `id`='246';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24400' WHERE `id`='247';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24500' WHERE `id`='248';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24600' WHERE `id`='241';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24700' WHERE `id`='242';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='24800' WHERE `id`='243';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='241' WHERE `id`='24100';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='242' WHERE `id`='24200';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='243' WHERE `id`='24300';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='244' WHERE `id`='24400';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='245' WHERE `id`='24500';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='246' WHERE `id`='24600';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='247' WHERE `id`='24700';
UPDATE `asterisk`.`endpointman_model_list` SET `id`='248' WHERE `id`='24800';
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('2411', '2', 'GXP2135', '4', 'general.json,accounts_4_lines.json,vpk_2135.json', '24', '0', '0');
UPDATE `asterisk`.`endpointman_model_list` SET `template_list`='general.json,accounts_3_lines.json,mpk_2130.json,vpk_2130.json' WHERE `id`='2410';
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('2412', '2', 'GXP2140', '4', 'general.json,accounts_4_lines.json,phonebook.json,softkeys_2140.json,vpk_2140.json,ext1_2140.json,ext2_2140.json,ext3_2140.json,ext4_2140.json', '24', '1', '0');
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('2413', '2', 'GXP2160', '6', 'general.json,accounts_6_lines.json,phonebook.json,softkeys_2160.json,mpk_2160.json,vpk_2160.json', '24', '1', '0');
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`) VALUES ('2414', '2', 'GXP2170', '6', 'general.json,accounts_6_lines.json,phonebook.json,vpk_2170.json,ext1_2170.json,ext2_2170.json,ext3_2170.json,ext4_2170.json', '24', '0');
UPDATE `asterisk`.`endpointman_product_list` SET `long_name`='GXP Enterprise HD series [2100,2110,2120,2130,2135,2140,2160,2170]' WHERE `id`='24';
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('261', '2', 'DP715', '5', 'general.json,profiles.json,handsets.json', '26', '0', '0');
INSERT INTO `asterisk`.`endpointman_product_list` (`id`, `brand`, `long_name`, `short_name`, `cfg_dir`, `config_files`) VALUES ('26', '2', 'DECT Cordless Phones [DP710,DP715]', 'DECT Cordless Phones', 'dp71x', 'cfg$mac');
INSERT INTO `asterisk`.`endpointman_model_list` (`id`, `brand`, `model`, `max_lines`, `template_list`, `product_id`, `enabled`, `hidden`) VALUES ('271', '2', 'HT701', '1', 'general.json', '27', '0', '0');
INSERT INTO `asterisk`.`endpointman_product_list` (`id`, `brand`, `long_name`, `short_name`, `cfg_dir`, `config_files`) VALUES ('27', '2', 'HandyTone ATA [HT701,HT702]', 'HandyTone ATA', 'ht70x', 'cfg$mac');

